version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install ODBC Driver
          command: |
            sudo apt-get install -y unixodbc-dev

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v --cov=dataviper

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            coverage run --source=dataviper -m pytest
            coverage report
            coverage html  # open htmlcov/index.html in a browser

      - store_artifacts:
          path: htmlcov
